import { getScorecardAction } from '@/lib/actions';
import type { MgnregaDataMonth } from '@/lib/types';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Wand2 } from 'lucide-react';

interface PerformanceScorecardProps {
  districtName: string;
  stateName: string;
  performanceData: MgnregaDataMonth[];
}

export default async function PerformanceScorecard({
  districtName,
  stateName,
  performanceData,
}: PerformanceScorecardProps) {
  const scorecard = await getScorecardAction(districtName, stateName, performanceData);

  // Split the scorecard into paragraphs for better formatting
  const paragraphs = scorecard.split('\n').filter(p => p.trim() !== '');

  return (
    <Card className="bg-primary/5 border-primary/20">
      <CardHeader>
        <div className="flex items-center gap-3">
            <Wand2 className="w-6 h-6 text-primary" />
            <CardTitle className="font-headline text-2xl text-primary">AI-Powered Summary</CardTitle>
        </div>
        <CardDescription>
          A simple summary of your district's performance over the last 6 months, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="prose prose-blue dark:prose-invert max-w-none text-base">
          {paragraphs.map((p, index) => (
            <p key={index}>{p}</p>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
